---
abstract: 'get debugging information from XML::LibXML nodes'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::9 version , CPAN::Meta::Converter version 2.140640'
keywords:
  - Debugging
  - XML
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-LibXML-Debugging
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  XML::LibXML::Debugging:
    file: lib/XML/LibXML/Debugging.pm
    version: '0.103'
requires:
  HTML::HTML5::Entities: '0'
  XML::LibXML: '0'
  parent: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/XML-LibXML-Debugging/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-LibXML-Debugging
  homepage: https://metacpan.org/release/XML-LibXML-Debugging
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-xml-libxml-debugging.git
version: '0.103'
